name: CI 

on:
  push:
    branches:
      - ParallelMatrixMultiplication
      - main
  pull_request:
    branches:
      - ParallelMatrixMultiplication
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
   
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ParallelMatrixMultiplication  
      
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  
      
      
      - name: Restore dependencies
        run: dotnet restore ParallelMM/ParallelMM/ParallelMM.csproj  
      
      
      - name: Build project
        run: dotnet build ParallelMM/Parallel
